// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8cwSiUX2_ymXSw6PkJqHXvRTEVFVQOQ',
    appId: '1:607339245535:web:83e0e3367ebd5c023c9e6a',
    messagingSenderId: '607339245535',
    projectId: 'class14-ac07e',
    authDomain: 'class14-ac07e.firebaseapp.com',
    storageBucket: 'class14-ac07e.firebasestorage.app',
    measurementId: 'G-DVENHWDCD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC3bxUTgpI1KwKLUKD1unlga56HGErqzM',
    appId: '1:607339245535:android:6d6a6c2d8f445a2d3c9e6a',
    messagingSenderId: '607339245535',
    projectId: 'class14-ac07e',
    storageBucket: 'class14-ac07e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO3FxEonk5iW9klXTg0NiGTl_XAOTK6PY',
    appId: '1:607339245535:ios:43834acda77d651b3c9e6a',
    messagingSenderId: '607339245535',
    projectId: 'class14-ac07e',
    storageBucket: 'class14-ac07e.firebasestorage.app',
    iosBundleId: 'com.example.inclass14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO3FxEonk5iW9klXTg0NiGTl_XAOTK6PY',
    appId: '1:607339245535:ios:43834acda77d651b3c9e6a',
    messagingSenderId: '607339245535',
    projectId: 'class14-ac07e',
    storageBucket: 'class14-ac07e.firebasestorage.app',
    iosBundleId: 'com.example.inclass14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk8cwSiUX2_ymXSw6PkJqHXvRTEVFVQOQ',
    appId: '1:607339245535:web:ee4f19e179c061613c9e6a',
    messagingSenderId: '607339245535',
    projectId: 'class14-ac07e',
    authDomain: 'class14-ac07e.firebaseapp.com',
    storageBucket: 'class14-ac07e.firebasestorage.app',
    measurementId: 'G-KDHZK6NW62',
  );
}
